import type { Doc, TreeItem } from '@docsmith/core'

// Just declare the types - the actual implementations
// will be generated by the plugin
export declare const docs: Doc[]
export declare const tree: TreeItem[]

export declare function getDoc(slug: string): Doc | null
export declare function getTree(): TreeItem[]
export declare function getDocs(): Doc[]
